-- Storage Hunters CRM: Market Intelligence foundation.
-- Idempotent — safe to run more than once. Applied to production and verified
-- through the live dashboard endpoint on 2026-07-27.
--
-- Before running:
-- 1. Download an in-app backup and confirm the encrypted GitHub backup artifact.
-- 2. Paste this file into the Supabase SQL Editor and run it.
-- 3. Refresh the app; the Dashboard degrades gracefully until this exists
--    (the intelligence API returns { migrationNeeded: true }).
--
-- Security model: these tables are written ONLY by the server-side service-role
-- client during ingestion. The publishable/anon key must not write news/market
-- rows. Read access for the app is served through the cached /api endpoint, not
-- by exposing these tables to the browser. RLS below denies anon by default;
-- the service-role key bypasses RLS.

-- ── Normalized news + official releases ──────────────────────────────────────
create table if not exists public.market_intelligence_items (
  id                bigint generated by default as identity primary key,
  canonical_url     text not null,
  provider          text not null,
  source_name       text,
  source_domain     text,
  title             text not null,
  published_at      timestamptz,
  discovered_at     timestamptz not null default now(),
  category          text,
  subcategory       text,
  tags              jsonb not null default '[]'::jsonb,
  raw_excerpt       text,
  summary           text,
  why_it_matters    text,
  broker_takeaway   text,
  relevance_score   integer,
  importance_score  integer,
  freshness_score   real,
  impact            text,
  confidence        text,
  entities          jsonb not null default '[]'::jsonb,
  content_hash      text,
  is_read           boolean not null default false,
  is_saved          boolean not null default false,
  is_hidden         boolean not null default false,
  provider_payload  jsonb,
  ai_model          text,
  ai_generated_at   timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint market_intelligence_items_canonical_url_key unique (canonical_url),
  constraint mii_relevance_bounds  check (relevance_score  is null or (relevance_score  between 0 and 100)),
  constraint mii_importance_bounds check (importance_score is null or (importance_score between 0 and 100)),
  constraint mii_category_check    check (category is null or category in
    ('self_storage','cre','rates','private_credit','private_equity','macro'))
);

create index if not exists idx_mii_published_at   on public.market_intelligence_items (published_at desc nulls last);
create index if not exists idx_mii_category        on public.market_intelligence_items (category);
create index if not exists idx_mii_importance      on public.market_intelligence_items (importance_score desc nulls last);
create index if not exists idx_mii_saved           on public.market_intelligence_items (is_saved) where is_saved;
create index if not exists idx_mii_hidden          on public.market_intelligence_items (is_hidden) where is_hidden;
create index if not exists idx_mii_content_hash    on public.market_intelligence_items (content_hash);

comment on table public.market_intelligence_items is
  'Normalized news/official-release metadata for the market intelligence terminal. Stores only excerpts + AI summaries, never full publisher article bodies.';

-- ── Normalized economic + rate observations ──────────────────────────────────
create table if not exists public.market_data_points (
  id               bigint generated by default as identity primary key,
  series_key       text not null,
  provider         text not null,
  observation_date date not null,
  value            double precision,
  unit             text,
  metadata         jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint market_data_points_uniq unique (provider, series_key, observation_date)
);

create index if not exists idx_mdp_series_date on public.market_data_points (series_key, observation_date desc);

comment on table public.market_data_points is
  'Time series of rates/economic observations (Treasury, FRED). One row per provider+series+observation_date.';

-- ── Generated daily brief snapshots ──────────────────────────────────────────
create table if not exists public.market_intelligence_snapshots (
  id                bigint generated by default as identity primary key,
  snapshot_date     date not null,
  generated_at      timestamptz not null default now(),
  headline          text,
  executive_brief   jsonb,
  market_regime     text,
  deal_environment  jsonb,
  top_item_ids      jsonb not null default '[]'::jsonb,
  market_metrics    jsonb,
  source_freshness  jsonb,
  evidence_item_ids jsonb not null default '[]'::jsonb,
  content_hash      text,
  ai_model          text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint market_intelligence_snapshots_date_key unique (snapshot_date)
);

comment on table public.market_intelligence_snapshots is
  'One synthesized daily brief per Eastern calendar date. Analytical synthesis with attached evidence item ids — not objective market prices.';

-- ── Ingestion run log (observability + concurrency guard) ────────────────────
create table if not exists public.market_intelligence_runs (
  id                bigint generated by default as identity primary key,
  run_key           text not null,
  trigger           text,
  status            text not null default 'running',
  started_at        timestamptz not null default now(),
  finished_at       timestamptz,
  items_discovered  integer not null default 0,
  items_inserted    integer not null default 0,
  items_updated     integer not null default 0,
  items_ai_processed integer not null default 0,
  provider_results  jsonb,
  errors            jsonb,
  created_at        timestamptz not null default now(),
  constraint market_intelligence_runs_run_key_key unique (run_key)
);

create index if not exists idx_mir_started_at on public.market_intelligence_runs (started_at desc);

comment on table public.market_intelligence_runs is
  'Idempotency + observability. A unique run_key (e.g. mode+eastern-hour-bucket) prevents two serverless invocations from processing the same bucket twice.';

-- ── updated_at maintenance ───────────────────────────────────────────────────
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists mii_touch_updated_at on public.market_intelligence_items;
create trigger mii_touch_updated_at before update on public.market_intelligence_items
  for each row execute function public.touch_updated_at();

drop trigger if exists mdp_touch_updated_at on public.market_data_points;
create trigger mdp_touch_updated_at before update on public.market_data_points
  for each row execute function public.touch_updated_at();

drop trigger if exists mis_touch_updated_at on public.market_intelligence_snapshots;
create trigger mis_touch_updated_at before update on public.market_intelligence_snapshots
  for each row execute function public.touch_updated_at();

-- ── Row-level security: deny anon; service-role (server) bypasses RLS ─────────
-- These tables are ingested and read server-side only. Enabling RLS with no
-- anon policy means the publishable key cannot read or write them directly,
-- while the service-role key used by the ingestion functions is unaffected.
alter table public.market_intelligence_items      enable row level security;
alter table public.market_data_points             enable row level security;
alter table public.market_intelligence_snapshots  enable row level security;
alter table public.market_intelligence_runs       enable row level security;

-- Rollback considerations:
-- - Dropping these tables discards cached intelligence; re-ingestion rebuilds it.
-- - To fully remove: drop the four tables, then drop function touch_updated_at
--   (only if no other object depends on it).
